name: 'Auto Merge Branches'
description: 'Automatically merge branches'
author: 'Yuval Cohen'
inputs:
  target_branch:
    required: true
    description: 'The target branch'
  message:
    required: true
    description: 'The merge commit message'
  github_token:
    required: true
    description: 'Github token'
  create_pull_request:
    required: true
    description: 'Create a pull request if there are conflicts'
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
