name: 'Auto Merge Branches'
description: 'Automatically merge branches'
author: 'Yuval Cohen'
inputs:
  target_branch:
    description: 'The target branch'
  target_branch_pattern:
    description: 'The target branch regex pattern'
  message:
    required: true
    description: 'The merge commit message'
  github_token:
    required: true
    description: 'Github token'
  create_pull_request:
    required: true
    description: 'Create a pull request if there are conflicts'
    default: 'true'
  add_pr_reviewer:
    required: true
    description: 'Add the commit owner as a reviewer on the pull request'
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
