name: 'test'
on:
  push:
    branches:
      - 'release/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          target_branch: develop
          message: Merge release to develop
          github_token: ${{ secrets.TOKEN }}
          create_pull_request: true
          add_assignee: false

